using System.Text;
using Microsoft.Kiota.Abstractions.Serialization;

namespace GrimoireCli.Tools.GenerateJsonExamples;

internal static class Program
{
    /// <summary>
    /// Usage: GenerateJsonExamples &lt;output path&gt;
    /// Emits a static class with a Type→JSON-sample dictionary for every model
    /// in the generated Kiota client, for --help-full to print as a request or
    /// response body template.
    /// </summary>
    public static int Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.Error.WriteLine("Usage: GenerateJsonExamples <output path>");
            return 1;
        }
        var outputPath = args[0];
        // SavedFile is the CLI's own --output receipt (a plain POCO, not a
        // Kiota model), so it never shows up in DiscoverModelTypes() but still
        // needs a sample for AddResponseExample<SavedFile>() to render.
        var types = DiscoverModelTypes().Append(typeof(GrimoireCli.Models.SavedFile)).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by tools/GenerateJsonExamples.");
        sb.AppendLine("//   Do not edit by hand — run `dotnet run --project tools/GenerateJsonExamples -- <path>`.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace GrimoireCli.Commands;");
        sb.AppendLine();
        sb.AppendLine("internal static class JsonExamples");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<Type, string> Samples = new()");
        sb.AppendLine("    {");
        foreach (var type in types.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            var sample = type == typeof(GrimoireCli.Models.SavedFile)
                ? "{\n  \"bytes\": 0,\n  \"path\": \"<string>\"\n}"
                : KiotaSampleWalker.Render(type);
            // Safe to use Type.FullName raw only because DiscoverModelTypes()
            // filters out !t.IsNested, so none of these names contain
            // FullName's '+' nested-type separator.
            sb.Append("        { typeof(").Append(type.FullName).AppendLine("),");
            sb.Append("          ").Append(Quote(sample)).AppendLine(" },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string For(Type type)");
        sb.AppendLine("        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($\"No JSON example registered for {type.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyDictionary<Type, string> All => Samples;");
        sb.AppendLine("}");

        // Normalise line endings so checked-in output is stable cross-platform.
        var content = sb.ToString().Replace("\r\n", "\n");
        File.WriteAllText(outputPath, content);
        Console.WriteLine($"Wrote {types.Count} samples to {outputPath}");
        return 0;
    }

    /// <summary>
    /// Every model in the generated client: the top-level IParsable classes of
    /// GrimoireCli.Generated.Models, covering both request bodies and response
    /// payloads. Excluded are the composed types' "…Member1" null-branch
    /// shells, which carry no fields, and HTTPValidationError /
    /// ValidationError, the spec's only response-only schemas.
    /// </summary>
    private static List<Type> DiscoverModelTypes()
    {
        var excluded = new HashSet<string> { "HTTPValidationError", "ValidationError" };
        return typeof(Generated.Models.GameSystemUpdate).Assembly
            .GetTypes()
            .Where(t => t.Namespace == "GrimoireCli.Generated.Models")
            .Where(t => t.IsClass && t.IsPublic && !t.IsNested && !t.IsAbstract)
            .Where(t => typeof(IParsable).IsAssignableFrom(t))
            .Where(t => !t.Name.EndsWith("Member1", StringComparison.Ordinal))
            .Where(t => !excluded.Contains(t.Name))
            .ToList();
    }

    private static string Quote(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";
}
