using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using GrimoireCli.Configuration;
using GrimoireCli.Models;

namespace GrimoireCli.Tools.GenerateResponseExamples;

internal static class Program
{
    /// <summary>
    /// Usage: GenerateResponseExamples &lt;output path&gt;
    /// Emits a static class with a Type→JSON-sample dictionary for every type
    /// registered on AppJsonContext via [JsonSerializable], skipping types that
    /// are not meaningful response payloads (auth request bodies, local config,
    /// Dictionary/List helper registrations).
    /// </summary>
    public static int Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.Error.WriteLine("Usage: GenerateResponseExamples <output path>");
            return 1;
        }
        var outputPath = args[0];
        var types = DiscoverResponseTypes();
        var overrides = BuildPropertyOverrides();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by tools/GenerateResponseExamples.");
        sb.AppendLine("//   Do not edit by hand — run `dotnet run --project tools/GenerateResponseExamples -- <path>`.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace GrimoireCli.Commands;");
        sb.AppendLine();
        sb.AppendLine("internal static class ResponseExamples");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<Type, string> Samples = new()");
        sb.AppendLine("    {");
        foreach (var type in types.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            var sample = SampleJsonWalker.Render(type, overrides);
            sb.Append("        { typeof(").Append(FullTypeName(type)).AppendLine("),");
            sb.Append("          ").Append(Quote(sample)).AppendLine(" },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string For(Type type)");
        sb.AppendLine("        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($\"No response example registered for {type.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyDictionary<Type, string> All => Samples;");
        sb.AppendLine("}");

        // Normalise line endings so checked-in output is stable cross-platform.
        var content = sb.ToString().Replace("\r\n", "\n");
        File.WriteAllText(outputPath, content);
        Console.WriteLine($"Wrote {types.Count} samples to {outputPath}");
        return 0;
    }

    /// <summary>
    /// Registers per-property overrides so the walker emits realistic sample
    /// values instead of the generic "&lt;string&gt;" / 0 placeholders, keyed by
    /// the declaring type so an override made on a base class (e.g.
    /// GameSystemSummary.Name) also applies when walking a derived type
    /// (GameSystemDetail).
    /// </summary>
    private static PropertyOverrides BuildPropertyOverrides()
    {
        var o = new PropertyOverrides();

        o.StringValues[(typeof(GameSystemSummary), nameof(GameSystemSummary.Name))] = "Shadowrun 6 DE";
        o.StringValues[(typeof(GameSystemSummary), nameof(GameSystemSummary.Slug))] = "shadowrun-6-de";
        o.StringValues[(typeof(GameSystemSummary), nameof(GameSystemSummary.Edition))] = "6";
        o.StringValues[(typeof(Book), nameof(Book.Category))] = "core";
        o.IntValues[(typeof(GameSystemSummary), nameof(GameSystemSummary.BookCount))] = 227;
        o.IntValues[(typeof(GameSystemSummary), nameof(GameSystemSummary.TotalPageCount))] = 6002;

        return o;
    }

    private static List<Type> DiscoverResponseTypes()
    {
        // Reflect over AppJsonContext's [JsonSerializable] attributes — the
        // single source of truth for types that cross the CLI↔server boundary.
        // Exclude types that aren't response payloads:
        //  - AppConfig (local config, never a response)
        //  - raw Dictionary/List helper registrations (not command responses;
        //    the array shape for GET /api/systems is composed at the call site
        //    by AddResponseExampleArray<T>)
        //  - request DTOs (GameSystemUpdateRequest and friends) — bodies, not payloads
        var excluded = new HashSet<Type>
        {
            typeof(AppConfig),
            typeof(GameSystemUpdateRequest),
            typeof(PublisherEntryRequest),
            typeof(LinkEntryRequest),
        };

        // JsonSerializableAttribute.Type is not a public property in .NET 8 —
        // the Type is only a constructor argument. Use CustomAttributeData to
        // retrieve it from the constructor arguments at runtime.
        var attrData = typeof(AppJsonContext)
            .GetCustomAttributesData()
            .Where(d => d.AttributeType == typeof(JsonSerializableAttribute));
        return attrData
            .Select(d => (Type)d.ConstructorArguments[0].Value!)
            .Where(t => !excluded.Contains(t))
            .Where(t => !IsCollectionHelperType(t))
            .ToList();
    }

    private static bool IsCollectionHelperType(Type t)
    {
        // Skip registrations like Dictionary<string,string> or List<GameSystemSummary>
        // — those exist to let STJ serialise helper shapes, not response payloads.
        if (!t.IsGenericType) return false;
        var def = t.GetGenericTypeDefinition();
        return def == typeof(Dictionary<,>) || def == typeof(List<>);
    }

    private static string FullTypeName(Type t)
    {
        // Emit without global:: prefix, with nested types using '.' syntax.
        var ns = t.Namespace ?? "";
        var name = t.Name;
        return string.IsNullOrEmpty(ns) ? name : $"{ns}.{name}";
    }

    private static string Quote(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";
}
