using System.Collections.Concurrent;
using System.CommandLine;
using System.CommandLine.Help;
using System.CommandLine.Invocation;
using System.Text;
using Microsoft.Kiota.Abstractions.Serialization;

namespace GrimoireCli.Commands;

public enum HelpSectionPosition { Top, Bottom }

/// <summary>
/// Adds custom sections (Notes, Examples, response shapes) to help output.
/// Top-positioned sections render before the default layout; Bottom-positioned
/// sections render after Options in registration order.
/// </summary>
public static class HelpExtensions
{
    private record Section(string Title, string[] Lines, HelpSectionPosition Position, bool IsShape = false);

    // ConcurrentDictionary so parallel xUnit test classes building independent
    // command trees can mutate the outer map without corrupting it. Each Command
    // instance is touched by exactly one thread, so the per-command List does
    // not need its own synchronization.
    private static readonly ConcurrentDictionary<Command, List<Section>> CommandSections = new();

    public static void AddHelpSection(this Command command, string title, params string[] lines)
        => command.AddHelpSection(title, HelpSectionPosition.Bottom, lines);

    public static void AddRoleRequired(this Command command, string role)
        => command.AddHelpSection("Role required", HelpSectionPosition.Top, role);

    public static void AddHelpSection(this Command command, string title, HelpSectionPosition position, params string[] lines)
    {
        var sections = CommandSections.GetOrAdd(command, _ => new List<Section>());
        sections.Add(new Section(title, lines, position));
    }

    /// <summary>
    /// Registers a response-shape section, hidden behind --help-full. Grimoire's
    /// OpenAPI spec types every response as an empty schema, so it's useless as a
    /// shape source; callers pass content derived from the DTOs instead — see
    /// <see cref="AddResponseExample{T}"/> and <see cref="AddResponseExampleArray{T}"/>,
    /// whose samples come from <c>ResponseExamples.g.cs</c> (generated by
    /// <c>tools/GenerateResponseExamples</c> from the DTOs on <c>AppJsonContext</c>
    /// and kept in sync by <c>ResponseExamplesDriftTest</c>).
    /// </summary>
    public static void AddShapeSection(this Command command, string title, params string[] lines)
    {
        var sections = CommandSections.GetOrAdd(command, _ => new List<Section>());
        sections.Add(new Section(title, lines, HelpSectionPosition.Bottom, IsShape: true));
    }

    /// <summary>Registers the generated response-shape sample for <typeparamref name="T"/>.</summary>
    public static void AddResponseExample<T>(this Command command)
        => command.AddShapeSection("Response shape", ResponseExamples.For(typeof(T)).Split('\n'));

    /// <summary>
    /// Registers a response-shape sample for an endpoint returning a bare array of
    /// <typeparamref name="T"/> rather than an envelope object — which is what
    /// GET /api/systems does — by wrapping the single-item sample in <c>[ ]</c>.
    /// </summary>
    public static void AddResponseExampleArray<T>(this Command command)
    {
        var element = ResponseExamples.For(typeof(T));
        var indented = string.Join('\n', element.Split('\n').Select(l => "  " + l));
        command.AddShapeSection("Response shape", $"[\n{indented}\n]".Split('\n'));
    }

    /// <summary>
    /// Registers the fields a request body may carry, read from the generated model
    /// for the endpoint and hidden behind --help-full beside the response shape.
    /// Names only: the generated model publishes its field names, and its property
    /// types are composed-type wrappers whose underlying scalar is not reachable
    /// without reflection that Native AOT trims. Nothing here is hand-written, so a
    /// field added to the API appears as soon as the client is regenerated.
    /// </summary>
    public static void AddRequestShape<T>(this Command command, T model, params string[] preamble)
        where T : IParsable
        => command.AddShapeSection("Request fields",
            [.. preamble, .. Wrap(model.GetFieldDeserializers().Keys.Order(StringComparer.Ordinal))]);

    private static IEnumerable<string> Wrap(IEnumerable<string> names, int width = 66)
    {
        var line = new StringBuilder();
        foreach (var name in names)
        {
            if (line.Length + name.Length + 2 > width)
            {
                yield return $"{line},";
                line.Clear();
            }
            line.Append(line.Length == 0 ? name : $", {name}");
        }
        yield return line.ToString();
    }

    public static void AddExamples(this Command command, params string[] examples)
        => command.AddHelpSection("Examples", HelpSectionPosition.Bottom, examples);

    public static int GetExampleCount(this Command command)
    {
        if (!CommandSections.TryGetValue(command, out var sections))
            return 0;
        return sections
            .Where(s => s.Title == "Examples")
            .SelectMany(s => s.Lines)
            .Count();
    }

    /// <summary>
    /// Replaces the default <see cref="HelpAction"/> on the root command's
    /// <see cref="HelpOption"/> with a wrapper that writes Top-positioned
    /// sections before the default layout and Bottom-positioned sections
    /// after it. The HelpOption is recursive by default, so the wrapper also
    /// fires for every subcommand <c>--help</c>.
    /// </summary>
    public static void UseCustomHelpSections(this RootCommand root)
    {
        var helpOption = root.Options.OfType<HelpOption>().FirstOrDefault()
            ?? throw new InvalidOperationException(
                "RootCommand has no HelpOption — cannot install CustomHelpAction.");
        if (helpOption.Action is not HelpAction defaultAction)
            throw new InvalidOperationException(
                $"HelpOption.Action is {helpOption.Action?.GetType().Name ?? "null"}, expected HelpAction.");
        helpOption.Action = new CustomHelpAction(defaultAction, includeShapes: false);
        var fullHelp = new Option<bool>("--help-full")
        {
            Description = "Show full help including the request and response shapes.",
            Recursive = true,
            Action = new CustomHelpAction(defaultAction, includeShapes: true),
        };
        root.Options.Add(fullHelp);
    }

    private sealed class CustomHelpAction : SynchronousCommandLineAction
    {
        private readonly HelpAction _inner;
        private readonly bool _includeShapes;
        public CustomHelpAction(HelpAction inner, bool includeShapes)
        {
            _inner = inner;
            _includeShapes = includeShapes;
        }

        public override int Invoke(ParseResult parseResult)
        {
            var command = parseResult.CommandResult.Command;
            var output = parseResult.InvocationConfiguration.Output;
            WriteSections(command, output, HelpSectionPosition.Top, _includeShapes);
            var rc = _inner.Invoke(parseResult);
            WriteSections(command, output, HelpSectionPosition.Bottom, _includeShapes);
            if (!_includeShapes) WriteShapeHint(command, output);
            return rc;
        }
    }

    private static void WriteShapeHint(Command command, TextWriter output)
    {
        if (!CommandSections.TryGetValue(command, out var sections)) return;
        if (!sections.Any(s => s.IsShape)) return;
        output.WriteLine("Run --help-full to see the request and response shapes.");
        output.WriteLine();
    }

    private static void WriteSections(Command command, TextWriter output, HelpSectionPosition position, bool includeShapes)
    {
        if (!CommandSections.TryGetValue(command, out var sections)) return;
        foreach (var section in sections.Where(s => s.Position == position))
        {
            if (section.IsShape && !includeShapes) continue;
            output.WriteLine($"{section.Title}:");
            foreach (var line in section.Lines)
                output.WriteLine($"  {line}");
            output.WriteLine();
        }
    }
}
