<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GrimoireCli</RootNamespace>
    <AssemblyName>grimoire-cli</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>0.1.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
    <PackageReference Include="NLog" Version="6.1.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GrimoireCli.Tests" />
  </ItemGroup>

</Project>
