using System.Text;
using Microsoft.Kiota.Abstractions.Serialization;

namespace GrimoireCli.Tools.GenerateRequestExamples;

internal static class Program
{
    /// <summary>
    /// Usage: GenerateRequestExamples &lt;output path&gt;
    /// Emits a static class with a Type→JSON-sample dictionary for every request
    /// model in the generated Kiota client, for --help-full to print as a body
    /// template.
    ///
    /// The emitter below is near-verbatim <c>tools/GenerateResponseExamples/Program.cs</c>'s
    /// — header, dictionary scaffolding, Quote, line-ending normalisation. That
    /// duplication is deliberate (the two tools' walkers are independent by
    /// design; see the design doc), so a change to the emitted format must be
    /// made in both places on purpose.
    /// </summary>
    public static int Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.Error.WriteLine("Usage: GenerateRequestExamples <output path>");
            return 1;
        }
        var outputPath = args[0];
        var types = DiscoverRequestTypes();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by tools/GenerateRequestExamples.");
        sb.AppendLine("//   Do not edit by hand — run `dotnet run --project tools/GenerateRequestExamples -- <path>`.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace GrimoireCli.Commands;");
        sb.AppendLine();
        sb.AppendLine("internal static class RequestExamples");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<Type, string> Samples = new()");
        sb.AppendLine("    {");
        foreach (var type in types.OrderBy(t => t.FullName, StringComparer.Ordinal))
        {
            var sample = KiotaSampleWalker.Render(type);
            // Unlike the response emitter's FullTypeName(), this uses Type.FullName
            // raw — safe only because DiscoverRequestTypes() filters out !t.IsNested,
            // so none of these names contain FullName's '+' nested-type separator.
            sb.Append("        { typeof(").Append(type.FullName).AppendLine("),");
            sb.Append("          ").Append(Quote(sample)).AppendLine(" },");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static string For(Type type)");
        sb.AppendLine("        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($\"No request example registered for {type.FullName}\");");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyDictionary<Type, string> All => Samples;");
        sb.AppendLine("}");

        // Normalise line endings so checked-in output is stable cross-platform.
        var content = sb.ToString().Replace("\r\n", "\n");
        File.WriteAllText(outputPath, content);
        Console.WriteLine($"Wrote {types.Count} samples to {outputPath}");
        return 0;
    }

    /// <summary>
    /// Every request model in the generated client: the top-level IParsable
    /// classes of GrimoireCli.Generated.Models. Excluded are the composed types'
    /// "…Member1" null-branch shells, which carry no fields, and
    /// HTTPValidationError / ValidationError, the spec's only response-only
    /// schemas.
    /// </summary>
    private static List<Type> DiscoverRequestTypes()
    {
        var excluded = new HashSet<string> { "HTTPValidationError", "ValidationError" };
        return typeof(Generated.Models.GameSystemUpdate).Assembly
            .GetTypes()
            .Where(t => t.Namespace == "GrimoireCli.Generated.Models")
            .Where(t => t.IsClass && t.IsPublic && !t.IsNested && !t.IsAbstract)
            .Where(t => typeof(IParsable).IsAssignableFrom(t))
            .Where(t => !t.Name.EndsWith("Member1", StringComparison.Ordinal))
            .Where(t => !excluded.Contains(t.Name))
            .ToList();
    }

    private static string Quote(string s)
        => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";
}
